In [1]:
import nselib

from nselib import capital_market

C:\Users\Harsh\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
nselib.trading_holiday_calendar()

CalenderNotFound:  Calender data Not found try after some time

In [3]:
capital_market.bhav_copy_with_delivery('27-05-2025')

ConnectionError: HTTPConnectionPool(host='nseindia.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000240CFF587D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

In [4]:
capital_market.block_deals_data(period='6M')

ConnectionError: HTTPConnectionPool(host='nseindia.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000240D148D3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

In [9]:
capital_market.bulk_deal_data(period='3M')

,Date,Symbol,SecurityName,ClientName,Buy/Sell,QuantityTraded,TradePrice/Wght.Avg.Price,Remarks,<!DOCTYPEhtml>
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<html lang=""en"">"
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<head>
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<meta charset=""UTF-8"">"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<title>Resource not found</title>
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,</head>
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<body style=""background-color: #e8e8e8;"">"
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<div style=""font-size: 32px; padding: 50px 2..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Resource not found
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,</div>
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<script type=""text/javascript"" src=""/-diU0StE..."
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,</html>

In [10]:
capital_market.deliverable_position_data('TATAMOTORS',period='6M')

,Symbol,Series,Date,TradedQty,DeliverableQty,%DlyQttoTradedQty,<!DOCTYPEhtml>
0,NaN,NaN,NaN,NaN,NaN,NaN,"<html lang=""en"">"
1,NaN,NaN,NaN,NaN,NaN,NaN,<head>
2,NaN,NaN,NaN,NaN,NaN,NaN,"<meta charset=""UTF-8"">"
3,NaN,NaN,NaN,NaN,NaN,NaN,<title>Resource not found</title>
4,NaN,NaN,NaN,NaN,NaN,NaN,</head>
5,NaN,NaN,NaN,NaN,NaN,NaN,"<body style=""background-color: #e8e8e8;"">"
6,NaN,NaN,NaN,NaN,NaN,NaN,"<div style=""font-size: 32px; padding: 50px 2..."
7,NaN,NaN,NaN,NaN,NaN,NaN,Resource not found
8,NaN,NaN,NaN,NaN,NaN,NaN,</div>
9,NaN,NaN,NaN,NaN,NaN,NaN,"<script type=""text/javascript"" src=""/-diU0StE..."
10,NaN,NaN,NaN,NaN,NaN,NaN,</html>

In [11]:
capital_market.price_volume_and_deliverable_position_data('CESC',period='6M')

,Symbol,Series,Date,PrevClose,OpenPrice,HighPrice,LowPrice,LastPrice,ClosePrice,AveragePrice,TotalTradedQuantity,TurnoverInRs,No.ofTrades,DeliverableQty,%DlyQttoTradedQty,<!DOCTYPEhtml>
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<html lang=""en"">"
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<head>
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<meta charset=""UTF-8"">"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<title>Resource not found</title>
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,</head>
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<body style=""background-color: #e8e8e8;"">"
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<div style=""font-size: 32px; padding: 50px 2..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Resource not found
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,</div>
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"<script type=""text/javascript"" src=""/-diU0StE..."
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,</html>

In [26]:
capital_market.price_volume_data('CDSL',period='1M')

,Symbol,Series,Date,PrevClose,OpenPrice,HighPrice,LowPrice,LastPrice,ClosePrice,AveragePrice,TotalTradedQuantity,Turnover,No.ofTrades,"ï»¿""Symbol""",Turnoverâ¹
0,NaN,EQ,07-Feb-2024,"1,850.35","1,866.90","1,998.85","1,848.00","1,954.80","1,957.95","1,955.11","59,72,762",NaN,"2,25,116",CDSL,"11,67,74,21,360.80"
1,NaN,EQ,08-Feb-2024,"1,957.95","1,978.00","2,044.00","1,919.00","2,000.00","2,000.30","1,998.05","36,10,129",NaN,"1,59,554",CDSL,"7,21,32,19,928.65"
2,NaN,EQ,09-Feb-2024,"2,000.30","2,012.00","2,067.00","1,916.10","1,950.00","1,946.95","1,976.78","27,20,850",NaN,"1,44,059",CDSL,"5,37,85,08,688.90"
3,NaN,EQ,12-Feb-2024,"1,946.95","1,958.00","1,958.95","1,825.00","1,847.85","1,849.85","1,894.59","14,01,587",NaN,"86,699",CDSL,"2,65,54,38,683.90"
4,NaN,EQ,13-Feb-2024,"1,849.85","1,849.85","1,900.00","1,807.35","1,879.00","1,885.50","1,864.71","11,95,658",NaN,"70,644",CDSL,"2,22,95,52,642.60"
5,NaN,EQ,14-Feb-2024,"1,885.50","1,848.00","1,907.00","1,837.70","1,899.25","1,898.70","1,887.47","8,16,478",NaN,"48,226",CDSL,"1,54,10,74,134.75"
6,NaN,EQ,15-Feb-2024,"1,898.70","1,912.65","1,916.45","1,871.65","1,880.00","1,878.40","1,893.25","5,63,632",NaN,"38,882",CDSL,"1,06,70,95,870.95"
7,NaN,EQ,16-Feb-2024,"1,878.40","1,883.00","1,906.00","1,870.10","1,874.00","1,876.15","1,884.24","5,96,658",NaN,"32,351",CDSL,"1,12,42,47,038.00"
8,NaN,EQ,19-Feb-2024,"1,876.15","1,868.40","1,883.55","1,832.00","1,842.90","1,841.50","1,853.37","5,91,969",NaN,"48,515",CDSL,"1,09,71,38,106.65"
9,NaN,EQ,20-Feb-2024,"1,841.50","1,843.95","1,866.50","1,835.00","1,842.50","1,841.30","1,849.92","4,86,031",NaN,"36,431",CDSL,"89,91,20,591.70"
10,NaN,EQ,21-Feb-2024,"1,841.30","1,842.00","1,856.95","1,786.35","1,797.00","1,799.60","1,819.36","5,68,555",NaN,"43,420",CDSL,"1,03,44,03,407.30"
11,NaN,EQ,22-Feb-2024,"1,799.60","1,807.00","1,828.90","1,793.00","1,824.00","1,824.65","1,814.86","4,80,392",NaN,"36,343",CDSL,"87,18,44,163.20"
12,NaN,EQ,23-Feb-2024,"1,824.65","1,835.00","1,877.70","1,814.70","1,859.50","1,859.55","1,851.72","9,57,638",NaN,"53,064",CDSL,"1,77,32,73,754.90"
13,NaN,EQ,26-Feb-2024,"1,859.55","1,859.55","1,938.50","1,842.05","1,900.00","1,900.00","1,910.31","18,96,223",NaN,"96,564",CDSL,"3,62,23,69,351.75"
14,NaN,EQ,27-Feb-2024,"1,900.00","1,912.05","1,960.00","1,902.70","1,915.90","1,913.95","1,931.84","14,79,422",NaN,"95,937",CDSL,"2,85,80,02,917.10"
15,NaN,EQ,28-Feb-2024,"1,913.95","1,923.00","1,980.00","1,917.00","1,925.00","1,931.05","1,954.19","21,28,319",NaN,"95,744",CDSL,"4,15,91,38,967.60"
16,NaN,EQ,29-Feb-2024,"1,931.05","1,934.80","1,934.80","1,882.85","1,920.00","1,917.15","1,910.60","9,66,164",NaN,"46,597",CDSL,"1,84,59,54,152.55"
17,NaN,EQ,01-Mar-2024,"1,917.15","1,925.00","1,958.00","1,908.10","1,915.05","1,918.55","1,929.35","6,35,328",NaN,"33,642",CDSL,"1,22,57,69,185.75"
18,NaN,EQ,02-Mar-2024,"1,918.55","1,923.50","1,933.00","1,912.95","1,930.10","1,929.60","1,926.89","87,871",NaN,"5,083",CDSL,"16,93,17,780.60"
19,NaN,EQ,04-Mar-2024,"1,929.60","1,938.95","1,944.80","1,892.20","1,903.00","1,900.75","1,908.38","5,47,337",NaN,"39,354",CDSL,"1,04,45,27,603.80"
20,NaN,EQ,05-Mar-2024,"1,900.75","1,904.00","1,907.70","1,873.60","1,883.00","1,879.65","1,885.66","3,92,464",NaN,"28,231",CDSL,"74,00,52,841.90"
21,NaN,EQ,06-Mar-2024,"1,879.65","1,880.00","1,880.00","1,810.10","1,838.00","1,836.80","1,837.56","6,80,849",NaN,"54,042",CDSL,"1,25,10,98,654.85"
22,NaN,EQ,07-Mar-2024,"1,836.80","1,853.00","1,858.65","1,825.80","1,833.00","1,830.60","1,837.47","4,81,857",NaN,"34,846",CDSL,"88,53,99,413.05"

In [27]:
capital_market.equity_list()

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,FACE VALUE
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5
1,21STCENMGM,21st Century Management Services Limited,BE,03-MAY-1995,10
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1
3,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10
4,3MINDIA,3M India Limited,EQ,13-AUG-2004,10
...,...,...,...,...,...
1955,ZOTA,Zota Health Care LImited,EQ,19-AUG-2019,10
1956,ZUARI,Zuari Agro Chemicals Limited,EQ,27-NOV-2012,10
1957,ZUARIIND,ZUARI INDUSTRIES LIMITED,EQ,12-APR-1995,10
1958,ZYDUSLIFE,Zydus Lifesciences Limited,EQ,18-APR-2000,1
1959,ZYDUSWELL,Zydus Wellness Limited,EQ,13-NOV-2009,10

In [28]:
capital_market.fno_equity_list()

                             Company_Name      Symbol       MAR-24
0    NIFTY MID SELECT                      MIDCPNIFTY  75
1    NIFTY FINANCIAL SERVICES              FINNIFTY    40
2    NIFTY BANK                            BANKNIFTY   15
3    NIFTY 50                              NIFTY       50
4    APOLLO HOSPITALS ENTER. L             APOLLOHOSP          125
..                                    ...         ...          ...
181  GAIL (INDIA) LTD                      GAIL               4575
182  NMDC LTD.                             NMDC               4500
183  JSW STEEL LIMITED                     JSWSTEEL            675
184  OBEROI REALTY LIMITED                 OBEROIRLTY          700
185  PVR INOX LIMITED                      PVRINOX             407

[186 rows x 3 columns]

In [1]:
capital_market.index_data('NIFTY ',period='1M')

NameError: name 'capital_market' is not defined

In [34]:
capital_market.india_vix_data(period='1M')

,TIMESTAMP,INDEX_NAME,OPEN_INDEX_VAL,CLOSE_INDEX_VAL,HIGH_INDEX_VAL,LOW_INDEX_VAL,PREV_CLOSE,VIX_PTS_CHG,VIX_PERC_CHG
0,07-FEB-2024,INDIA VIX,15.7850,15.5050,16.0175,14.7400,15.7850,-0.2800,-1.773836
1,08-FEB-2024,INDIA VIX,15.5050,15.8275,16.0275,15.2425,15.5050,0.3225,2.079974
2,09-FEB-2024,INDIA VIX,15.8275,15.4475,16.3325,15.2650,15.8275,-0.3800,-2.400885
3,12-FEB-2024,INDIA VIX,15.4475,16.0625,16.5350,15.4475,15.4475,0.6150,3.981227
4,13-FEB-2024,INDIA VIX,16.0625,15.8075,16.5700,15.7525,16.0625,-0.2550,-1.587549
5,14-FEB-2024,INDIA VIX,15.8075,15.4350,16.1975,15.3400,15.8075,-0.3725,-2.356476
6,15-FEB-2024,INDIA VIX,15.4350,15.2250,15.6625,15.1125,15.4350,-0.2100,-1.360544
7,16-FEB-2024,INDIA VIX,15.2250,15.2225,15.5525,14.9025,15.2250,-0.0025,-0.016420
8,19-FEB-2024,INDIA VIX,15.2225,16.0175,16.1175,13.7000,15.2225,0.7950,5.222532
9,20-FEB-2024,INDIA VIX,16.0175,16.0725,16.3600,14.2125,16.0175,0.0550,0.343374
10,21-FEB-2024,INDIA VIX,16.0725,15.9275,16.3100,15.6800,16.0725,-0.1450,-0.902162
11,22-FEB-2024,INDIA VIX,15.9275,15.1975,16.1500,15.1325,15.9275,-0.7300,-4.583268
12,23-FEB-2024,INDIA VIX,15.1975,14.9725,15.4425,14.8400,15.1975,-0.2250,-1.480507
13,26-FEB-2024,INDIA VIX,14.9725,15.6000,15.9600,13.7575,14.9725,0.6275,4.191017
14,27-FEB-2024,INDIA VIX,15.6000,15.7275,15.9975,15.5300,15.6000,0.1275,0.817308
15,28-FEB-2024,INDIA VIX,15.7275,16.3300,16.7400,15.3100,15.7275,0.6025,3.830869
16,29-FEB-2024,INDIA VIX,16.3300,15.5725,16.5525,15.3700,16.3300,-0.7575,-4.638702
17,01-MAR-2024,INDIA VIX,15.5725,15.2350,15.6425,15.0000,15.5725,-0.3375,-2.167282
18,02-MAR-2024,INDIA VIX,15.2350,14.9925,15.4150,13.5300,15.2350,-0.2425,-1.591730
19,04-MAR-2024,INDIA VIX,14.9925,14.9225,15.3025,14.8225,14.9925,-0.0700,-0.466900
20,05-MAR-2024,INDIA VIX,14.9225,14.3800,15.1650,14.1775,14.9225,-0.5425,-3.635450
21,06-MAR-2024,INDIA VIX,14.3800,14.2950,14.7100,13.9050,14.3800,-0.0850,-0.591099
22,07-MAR-2024,INDIA VIX,14.2950,13.6125,14.4325,13.5600,14.2950,-0.6825,-4.774397

In [35]:
capital_market.market_watch_all_indices()

,key,index,indexSymbol,last,variation,percentChange,open,high,low,previousClose,...,dy,declines,advances,unchanged,perChange365d,perChange30d,previousDay,oneWeekAgo,oneMonthAgo,oneYearAgo
0,BROAD MARKET INDICES,NIFTY 50,NIFTY 50,22493.55,19.50,0.09,22505.30,22525.65,22430.00,22474.05,...,1.19,20,30,0,27,3.32,22356.30,21982.80,21771.70,17711.45
1,BROAD MARKET INDICES,NIFTY NEXT 50,NIFTY NEXT 50,60323.90,517.80,0.87,59934.65,60573.10,59929.10,59806.10,...,1.28,22,28,0,57.46,8.36,59981.35,58991.35,55669.85,38310.55
2,BROAD MARKET INDICES,NIFTY 100,NIFTY 100,23036.05,47.70,0.21,23024.05,23070.65,22970.85,22988.35,...,1.18,42,59,0,31.59,4.17,22900.65,22526.30,22113.40,17506.30
3,BROAD MARKET INDICES,NIFTY 200,NIFTY 200,12417.25,26.00,0.21,12410.60,12441.30,12386.75,12391.25,...,1.13,84,115,2,35.12,3.69,12361.55,12160.45,11975.65,9190.05
4,BROAD MARKET INDICES,NIFTY 500,NIFTY 500,20434.80,55.25,0.27,20413.65,20471.35,20384.50,20379.55,...,1.09,205,292,4,37.32,2.93,20382.00,20090.05,19853.50,14881.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,FIXED INCOME INDICES,NIFTY 10 YR BENCHMARK G-SEC (CLEAN PRICE),NIFTY GS 10YR CLN,879.10,1.53,0.17,877.57,879.12,877.57,877.57,...,,NaN,NaN,NaN,2.3,0.37,877.27,876.58,875.84,859.37
69,FIXED INCOME INDICES,NIFTY 4-8 YR G-SEC INDEX,NIFTY GS 4 8YR,2787.81,2.58,0.09,2785.77,2787.81,2785.77,2785.23,...,,NaN,NaN,NaN,8.66,0.48,2783.92,2782.06,2774.54,2565.55
70,FIXED INCOME INDICES,NIFTY 11-15 YR G-SEC INDEX,NIFTY GS 11 15YR,2845.71,4.03,0.14,2842.24,2845.71,2842.24,2841.68,...,,NaN,NaN,NaN,10.76,0.79,2840.69,2835.32,2823.36,2569.16
71,FIXED INCOME INDICES,NIFTY 15 YR AND ABOVE G-SEC INDEX,NIFTY GS 15YRPLUS,3156.33,5.34,0.16,3151.60,3157.20,3151.35,3150.99,...,,NaN,NaN,NaN,12.17,1.18,3150.44,3137.66,3119.59,2813.89
72,FIXED INCOME INDICES,NIFTY COMPOSITE G-SEC INDEX,NIFTY GS COMPSITE,2669.07,4.14,0.15,2665.45,2669.26,2665.45,2664.93,...,,NaN,NaN,NaN,9.8,0.88,2663.98,2658.56,2645.70,2430.87

In [12]:
capital_market.nifty50_equity_list()

,Company Name,Industry,Symbol
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT
4,Axis Bank Ltd.,Financial Services,AXISBANK
5,Bajaj Auto Ltd.,Automobile and Auto Components,BAJAJ-AUTO
6,Bajaj Finance Ltd.,Financial Services,BAJFINANCE
7,Bajaj Finserv Ltd.,Financial Services,BAJAJFINSV
8,Bharat Electronics Ltd.,Capital Goods,BEL
9,Bharti Airtel Ltd.,Telecommunication,BHARTIARTL
10,Cipla Ltd.,Healthcare,CIPLA
11,Coal India Ltd.,Oil Gas & Consumable Fuels,COALINDIA
12,Dr. Reddy's Laboratories Ltd.,Healthcare,DRREDDY
13,Eicher Motors Ltd.,Automobile and Auto Components,EICHERMOT
14,Eternal Ltd.,Consumer Services,ETERNAL
15,Grasim Industries Ltd.,Construction Materials,GRASIM
16,HCL Technologies Ltd.,Information Technology,HCLTECH
17,HDFC Bank Ltd.,Financial Services,HDFCBANK
18,HDFC Life Insurance Company Ltd.,Financial Services,HDFCLIFE
19,Hero MotoCorp Ltd.,Automobile and Auto Components,HEROMOTOCO
20,Hindalco Industries Ltd.,Metals & Mining,HINDALCO
21,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,HINDUNILVR
22,ICICI Bank Ltd.,Financial Services,ICICIBANK
23,ITC Ltd.,Fast Moving Consumer Goods,ITC
24,IndusInd Bank Ltd.,Financial Services,INDUSINDBK
25,Infosys Ltd.,Information Technology,INFY
26,JSW Steel Ltd.,Metals & Mining,JSWSTEEL
27,Jio Financial Services Ltd.,Financial Services,JIOFIN
28,Kotak Mahindra Bank Ltd.,Financial Services,KOTAKBANK
29,Larsen & Toubro Ltd.,Construction,LT
30,Mahindra & Mahindra Ltd.,Automobile and Auto Components,M&M
31,Maruti Suzuki India Ltd.,Automobile and Auto Components,MARUTI
32,NTPC Ltd.,Power,NTPC
33,Nestle India Ltd.,Fast Moving Consumer Goods,NESTLEIND
34,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,ONGC
35,Power Grid Corporation of India Ltd.,Power,POWERGRID
36,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,RELIANCE
37,SBI Life Insurance Company Ltd.,Financial Services,SBILIFE
38,Shriram Finance Ltd.,Financial Services,SHRIRAMFIN
39,State Bank of India,Financial Services,SBIN
40,Sun Pharmaceutical Industries Ltd.,Healthcare,SUNPHARMA
41,Tata Consultancy Services Ltd.,Information Technology,TCS
42,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,TATACONSUM
43,Tata Motors Ltd.,Automobile and Auto Components,TATAMOTORS
44,Tata Steel Ltd.,Metals & Mining,TATASTEEL
45,Tech Mahindra Ltd.,Information Technology,TECHM
46,Titan Company Ltd.,Consumer Durables,TITAN
47,Trent Ltd.,Consumer Services,TRENT
48,UltraTech Cement Ltd.,Construction Materials,ULTRACEMCO
49,Wipro Ltd.,Information Technology,WIPRO

In [13]:
capital_market.short_selling_data(period='1M')

,Date,Symbol,SecurityName,Quantity,<!DOCTYPEhtml>
0,NaN,NaN,NaN,NaN,"<html lang=""en"">"
1,NaN,NaN,NaN,NaN,<head>
2,NaN,NaN,NaN,NaN,"<meta charset=""UTF-8"">"
3,NaN,NaN,NaN,NaN,<title>Resource not found</title>
4,NaN,NaN,NaN,NaN,</head>
5,NaN,NaN,NaN,NaN,"<body style=""background-color: #e8e8e8;"">"
6,NaN,NaN,NaN,NaN,"<div style=""font-size: 32px; padding: 50px 2..."
7,NaN,NaN,NaN,NaN,Resource not found
8,NaN,NaN,NaN,NaN,</div>
9,NaN,NaN,NaN,NaN,"<script type=""text/javascript"" src=""/-diU0StE..."
10,NaN,NaN,NaN,NaN,</html>

In [14]:
import bsedata as bse

In [15]:
from bsedata.bse import BSE

bse = BSE(update_codes = True)

In [16]:
stock_data = bse.getQuote('500325')   #Reliance Industries Ltd. stock code is '500325'
print(stock_data)

{'companyName': 'Reliance Industries Ltd', 'currentValue': '1421.75', 'change': '-12.40', 'pChange': '-0.86', 'updatedOn': '27 May 25 | 04:00 PM', 'securityID': 'RELIANCE', 'scripCode': '500325', 'group': 'A  / BSE SENSEX', 'faceValue': '10.00', 'industry': 'Oil, Gas & Consumable Fuels', 'previousClose': '1434.15', 'previousOpen': '1429.15', 'dayHigh': '1437.30', 'dayLow': '1414.00', '52weekHigh': '1608.95', '52weekLow': '1115.55', 'weightedAvgPrice': '1421.71', 'totalTradedValue': '185.25 Cr.', 'totalTradedQuantity': '13.03 Lakh', '2WeekAvgQuantity': '5.28 Lakh', 'marketCapFull': '19,23,979.30 Cr.', 'marketCapFreeFloat': '9,60,581.30 Cr.', 'buy': {'1': {'quantity': '-', 'price': '0.00'}, '2': {'quantity': '-', 'price': '0.00'}, '3': {'quantity': '-', 'price': '0.00'}, '4': {'quantity': '-', 'price': '0.00'}, '5': {'quantity': '-', 'price': '0.00'}}, 'sell': {'1': {'price': '0.00', 'quantity': '-'}, '2': {'price': '0.00', 'quantity': '-'}, '3': {'price': '0.00', 'quantity': '-'}, '4': {'price': '0.00', 'quantity': '-'}, '5': {'price': '0.00', 'quantity': '-'}}}

In [7]:
bse.topGainers()  # Retrieves data for top gainers

[{'securityID': 'RALLIS',
  'scripCode': '500355',
  'LTP': '287.95',
  'change': '33.50',
  'pChange': '13.17'},
 {'securityID': 'TATACHEM',
  'scripCode': '500770',
  'LTP': '1,314.90',
  'change': '136.35',
  'pChange': '11.57'},
 {'securityID': 'FORCEMOT',
  'scripCode': '500033',
  'LTP': '6,484.75',
  'change': '589.50',
  'pChange': '10.00'},
 {'securityID': 'IIFL',
  'scripCode': '532636',
  'LTP': '420.40',
  'change': '37.60',
  'pChange': '9.82'},
 {'securityID': 'TTML',
  'scripCode': '532371',
  'LTP': '89.89',
  'change': '6.54',
  'pChange': '7.85'}]

In [55]:

bse.topLosers()   # Retrieves data for top losers

[{'securityID': 'JPASSOCIAT',
  'scripCode': '532532',
  'LTP': '17.85',
  'change': '-0.85',
  'pChange': '-4.55'},
 {'securityID': 'HBLPOWER',
  'scripCode': '517271',
  'LTP': '466.90',
  'change': '-20.95',
  'pChange': '-4.29'},
 {'securityID': 'PRICOLLTD',
  'scripCode': '540293',
  'LTP': '357.65',
  'change': '-14.55',
  'pChange': '-3.91'},
 {'securityID': 'NLCINDIA',
  'scripCode': '513683',
  'LTP': '218.20',
  'change': '-8.50',
  'pChange': '-3.75'},
 {'securityID': 'M&M',
  'scripCode': '500520',
  'LTP': '1,896.25',
  'change': '-72.45',
  'pChange': '-3.68'}]

In [8]:
bse.getIndices('market_cap')

### Invalid category ###
Use one of the categories mentioned below:

market_cap/broad
sector_and_industry
thematics
strategy
sustainability
volatility
composite
government
corporate
money_market

In [66]:
bse.getScripCodes()

{'533022': '20 Microns Ltd.',
 '532628': '3i Infotech Ltd.',
 '523395': '3m India Ltd.',
 '590116': '7seas Technologies Ltd-$',
 '512161': '8k Miles Software Services Ltd.',
 '538351': 'A.f. Enterprises Ltd',
 '539300': 'A.k. Spintex Ltd',
 '530499': 'A.k.capital Services Ltd.',
 '533292': 'A2z Infra Engineering Limited',
 '531611': 'Aadhaar Ventures India Ltd.',
 '530027': 'Aadi Industries Ltd.',
 '531866': 'Aagam Capital Ltd.',
 '539096': 'Aananda Lakshmi Spinning Mills Ltd',
 '538812': 'Aanchal Ispat Ltd',
 '524412': 'Aarey Drugs & Pharmaceuticals Ltd.',
 '524348': 'Aarti Drugs Ltd.',
 '524208': 'Aarti Industries Ltd.',
 '514274': 'Aarvee Denims & Exports Ltd.',
 '531731': 'Aarya Global Shares And Securities Ltd.',
 '519319': 'Aashee Infotech Ltd.',
 '512038': 'Aaswa Trading & Exports Ltd.',
 '523204': 'Aban Offshore Ltd.',
 '512165': 'Abans Enterprises Ltd',
 '500002': 'Abb India Limited',
 '500488': 'Abbott India Ltd.',
 '505665': 'Abc Bearings Ltd.-$',
 '513119': 'Abc Gas (international) Ltd.',
 '520123': 'Abc India Ltd.-$',
 '532682': 'Abg Shipyard Ltd.',
 '532057': 'Abhinav Capital Services Ltd.',
 '538952': 'Abhinav Leasing & Finance Ltd',
 '532831': 'Abhishek Corporation Ltd.',
 '538935': 'Abhishek Finlease Ltd',
 '511756': 'Abirami Financial Services (india) Ltd.',
 '526955': 'Abl Biotechnologies Ltd.',
 '531161': 'Abm Knowledgeware Ltd.',
 '500410': 'Acc Ltd.',
 '532774': 'Accel Frontline Ltd.',
 '517494': 'Accel Transmatic Ltd.',
 '532268': 'Accelya Kale Solutions Limitd',
 '531897': 'Accentia Technologies Ltd.-$',
 '526347': 'Acclaim Industries Limited',
 '530513': 'Accurate Transformers Ltd.',
 '530093': 'Ace Edutrend Ltd',
 '531525': 'Ace Software Exports Ltd.-$',
 '536492': 'Ace Tours Worldwide Ltd',
 '538570': 'Achal Investments Ltd',
 '517356': 'Aci Infocom Ltd.',
 '530901': 'Acil Cotton Industries Limited',
 '530043': 'Acknit Industries Ltd.',
 '539391': 'Acme Resources Ltd',
 '533330': 'Acropetal Technologies Ltd.',
 '513149': 'Acrow India Ltd.',
 '524091': 'Acrysil Ltd.',
 '532762': 'Action Construction Equipment Ltd.',
 '511706': 'Action Financial Services (india) Ltd.',
 '511359': 'Ad-manum Finance Ltd.',
 '512599': 'Adani Enterprises Ltd.',
 '532921': 'Adani Ports And Special Economic Zone Ltd.',
 '533096': 'Adani Power Ltd.',
 '539254': 'Adani Transmission Ltd',
 '538563': 'Adarsh Mercantile Ltd',
 '526711': 'Adarsh Plant Protect Ltd.',
 '523411': 'Adc India Communications Limited-$',
 '538734': 'Adcc Infocad Ltd',
 '507852': 'Addi Industries Ltd.-$',
 '519183': 'Adf Foods Ltd.-$',
 '539189': 'Adhbhut Infrastructure Ltd',
 '538365': 'Adhunik Industries Ltd',
 '532727': 'Adhunik Metaliks Ltd.',
 '530117': 'Adi Finechem Ltd.',
 '531592': 'Adi Rasayan Ltd.',
 '590088': 'Adinath Bio-labs Ltd.',
 '532056': 'Adinath Exim Resources Ltd.',
 '514113': 'Adinath Textiles Ltd.',
 '500057': 'Aditya Birla Chemicals (india) Ltd.',
 '535755': 'Aditya Birla Fashion And Retail Ltd',
 '532974': 'Aditya Birla Money Ltd.-$',
 '500303': 'Aditya Birla Nuvo Ltd.',
 '522150': 'Aditya Forge Ltd.',
 '513513': 'Aditya Ispat Ltd.',
 '521141': 'Aditya Spinners Ltd.',
 '539056': 'Adlabs Entertainment Ltd',
 '530431': 'Ador Fontech Ltd.-$',
 '523120': 'Ador Multiproducts Ltd.',
 '517041': 'Ador Welding Ltd.',
 '523031': 'Ads Diagnostic Ltd.',
 '521048': 'Advance Lifestyles Ltd.',
 '534612': 'Advance Metering Technology Ltd.',
 '506947': 'Advance Petrochemicals Ltd.',
 '531047': 'Advance Powerinfra Tech Limited',
 '517552': 'Advanced Micronic Devices Ltd.-$',
 '523269': 'Advani Hotels & Resorts (india) Ltd.',
 '532840': 'Advanta Limited',
 '531429': 'Advent Computer Services Ltd.',
 '531686': 'Advik Laboratories Ltd.',
 '500003': 'Aegis Logistics Ltd.',
 '530707': 'Aftek Ltd.',
 '531921': 'Agarwal Industrial Corporation Ltd.',
 '500463': 'Agc Networks Limited',
 '539042': 'Agi Infra Ltd',
 '516020': 'Agio Paper & Industries Ltd.-$',
 '537292': 'Agri- Tech (india) Ltd',
 '537492': 'Agrimony Commodities Ltd',
 '519281': 'Agro Dutch Industries Ltd.',
 '500215': 'Agro Tech Foods Ltd.',
 '524448': 'Ahlcon Parenterals (india) Ltd.',
 '532811': 'Ahluwalia Contracts (india) Ltd.',
 '522273': 'Ahmedabad Steelcraft Ltd.',
 '532806': 'Ai Champdany Industries Ltd.',
 '532683': 'Aia Engineering Ltd.',
 '506822': 'Aikyam Intellectual Property Consultancy Limited',
 '524288': 'Aimco Pesticides Ltd.',
 '532975': 'Aishwarya Telecom Ltd.',
 '532331': 'Ajanta Pharma Ltd.',
 '519216': 'Ajanta Soya Ltd.',
 '511692': 'Ajcon Global Services Ltd.',
 '530713': 'Ajel Ltd.',
 '513349': 'Ajmera Realty & Infra India Ltd.',
 '526628': 'Ajwa Fun World & Resort Ltd.',
 '530621': 'Akar Tools Ltd.',
 '538778': 'Akashdeep Metal Industries Ltd',
 '539017': 'Akme Star Housing Finance Ltd',
 '532351': 'Aksh Optifibre Ltd.',
 '524598': 'Aksharchem (india) Ltd.-$',
 '500710': 'Akzo Nobel India Limited',
 '535916': 'Alacrity Securities Ltd',
 '539115': 'Alan Scott Industries Ltd',
 '531517': 'Alang Industrial Gases Ltd.',
 '531082': 'Alankit Ltd',
 '524075': 'Albert David Ltd.-$',
 '531409': 'Alchemist Corporation Ltd.',
 '526707': 'Alchemist Ltd.',
 '532114': 'Alchemist Realty Ltd.',
 '506235': 'Alembic Ltd.',
 '533573': 'Alembic Pharmaceuticals Ltd.',
 '530973': 'Alfa Ica (india) Ltd.',
 '517546': 'Alfa Transformers Ltd.',
 '531156': 'Alfavision Overseas (india) Ltd.',
 '505216': 'Alfred Herbert (india) Ltd.',
 '531147': 'Alicon Castalloy Limited',
 '531581': 'Alka Diamond Industries Ltd.',
 '530889': 'Alka India Ltd.',
 '532166': 'Alka Securities Ltd.',
 '533029': 'Alkali Metals Ltd.',
 '506767': 'Alkyl Amines Chemicals Ltd.-$',
 '532480': 'Allahabad Bank',
 '532749': 'Allcargo Logistics Ltd.',
 '534064': 'Alliance Integrated Metaliks Ltd.',
 '532919': 'Allied Computers International (asia) Ltd.',
 '532875': 'Allied Digital Services Ltd.',
 '532633': 'Allsec Technologies Ltd.',
 '531400': 'Almondz Global Securities Ltd.',
 '506120': 'Alna Trading & Exports Ltd.',
 '521070': 'Alok Industries Ltd.',
 '532878': 'Alpa Laboratories Ltd.',
 '531720': 'Alpha Graphic India Ltd.',
 '531247': 'Alpha Hi-tech Fuel Ltd.',
 '526397': 'Alphageo (india) Ltd.-$',
 '526519': 'Alpine Housing Development Corporation Ltd.',
 '530715': 'Alps Industries Ltd.',
 '532309': 'Alstom India Ltd',
 '522275': 'Alstom T&d India Ltd.',
 '539277': 'Alstone Textiles (india) Ltd',
 '524634': 'Alufluoride Ltd.',
 '506597': 'Amal Ltd.',
 '501622': 'Amalgamated Electricity Co.ltd.',
 '512008': 'Amani Trading & Exports Ltd.',
 '532664': 'Amar Remedies Ltd.',
 '500008': 'Amara Raja Batteries Ltd.',
 '521097': 'Amarjothi Spinning Mills Ltd.',
 '538465': 'Amarnath Securities Ltd',
 '539196': 'Amba Enterprises Ltd',
 '500009': 'Ambalal Sarabhai Enterprises Ltd.',
 '532335': 'Ambica Agarbathies & Aroma Industries Ltd.',
 '531978': 'Ambika Cotton Mills Ltd.',
 '539223': 'Ambition Mica Ltd',
 '526439': 'Ambitious Plastomac Company Ltd.',
 '500425': 'Ambuja Cements Ltd.',
 '530133': 'Amco India Ltd.-$',
 '532828': 'Amd Industries Ltd.',
 '513117': 'Amforge Industries Ltd.',
 '506248': 'Amines & Plasticizers Ltd.',
 '531300': 'Amit International Ltd.',
 '531557': 'Amit Securities Ltd.',
 '521076': 'Amit Spinning Industries Ltd.',
 '531681': 'Amradeep Industries Ltd.',
 '536737': 'Amrapali Capital And Finance Services Ltd',
 '539265': 'Amrapali Fincap Ltd',
 '526241': 'Amrapali Industries Ltd.',
 '531991': 'Amraworld Agrico Ltd.',
 '507525': 'Amrit Corp.ltd.-$',
 '590006': 'Amrutanjan Health Care Ltd.-$',
 '538861': 'Amsons Apparels Ltd',
 '520077': 'Amtek Auto Ltd.-$',
 '531761': 'Amulya Leasing & Finance Ltd.',
 '531678': 'Anand Credit Ltd.',
 '501630': 'Anand Projects Ltd',
 '515055': 'Anant Raj Limited-$',
 '526833': 'Ananthi Constructions Ltd.',
 '531127': 'Anar Industries Ltd.',
 '532418': 'Andhra Bank',
 '532141': 'Andhra Cements Ltd.',
 '500012': 'Andhra Petrochemicals Ltd.',
 '590062': 'Andhra Sugars Ltd.',
 '526173': 'Andrew Yule & Company Ltd.',
 '530721': 'Ang Industries Limited',
 '519383': 'Anik Industries Ltd.',
 '532910': 'Anil Ltd.',
 '504629': 'Anil Special Steel Industries Ltd.-$',
 '537785': 'Anisha Impex Ltd',
 '531878': 'Anjani Finance Ltd.',
 '511153': 'Anjani Foods Ltd',
 '518091': 'Anjani Portland Cement Ltd.-$',
 '531223': 'Anjani Synthetics Ltd.-$',
 '531673': 'Anka India Ltd.',
 '532870': 'Ankit Metal & Power Ltd.',
 '531519': 'Ankush Finstock Ltd.',
 '530799': 'Anna Infrastructures Ltd.',
 '531406': 'Ans Industries Ltd',
 '523007': 'Ansal Buildwell Ltd.-$',
 '507828': 'Ansal Housing & Construction Ltd.-$',
 '500013': 'Ansal Properties & Infrastructure Ltd.',
 '512091': 'Anshuni Commercials Ltd.',
 '534707': 'Anshus Clothing Ltd.',
 '532981': "Anu's Laboratories Ltd.",
 '538833': 'Anubhav Infrastructure Ltd',
 '506260': 'Anuh Pharma Ltd.',
 '512355': 'Anukaran Commercial Enterprises Ltd.',
 '506087': 'Anup Malleable Ltd.',
 '532259': 'Apar Industries Ltd.',
 '523694': 'Apcotex Industries Ltd.',
 '506166': 'Apis India Ltd.',
 '533758': 'Apl Apollo Tubes Ltd.',
 '517096': 'Aplab Ltd.-$',
 '511064': 'Aplaya Creations Ltd',
 '523537': 'Apm Industries Ltd.-$',
 '512437': 'Apollo Finvest (india) Ltd.',
 '508869': 'Apollo Hospitals Enterprise Ltd.',
 '500877': 'Apollo Tyres Ltd.',
 '500014': 'Apple Finance Ltd.',
 '538653': 'Appu Marketing & Manufacturing Ltd',
 '507265': 'Apte Amalgamations Ltd.',
 '532475': 'Aptech Ltd.',
 '535790': 'Aptechbbph',
 '533159': 'Aqua Logistics Ltd',
 '531364': 'Aqua Pumps Infra Ventures Limited',
 '539403': 'Arambhan Hospitality Services Ltd',
 '532068': 'Aramusk Infrastructure Investments Ltd.',
 '512344': 'Aravali Securities & Finance Ltd.',
 '520121': 'Arcee Industries Ltd.',
 '530565': 'Archana Software Ltd.',
 '532994': 'Archidply Industries Ltd.',
 '532212': 'Archies Ltd.',
 '524640': 'Archit Organosys Ltd.',
 '511038': 'Arco Leasing Ltd.',
 '532914': 'Arcotech Ltd.',
 '530261': 'Arcuttipore Tea Co.ltd.',
 '504370': 'Ardi Investment & Trading Ltd.',
 '526851': 'Arex Industries Ltd.',
 '539151': 'Arfin India Ltd',
 '509110': 'Ari Consolidated Investments Ltd.',
 '532935': 'Aries Agro Ltd.',
 '531553': 'Arihant Avenues & Credit Ltd.',
 '511605': 'Arihant Capital Markets Ltd.',
 '531381': 'Arihant Foundations & Housing Ltd.-$',
 '506194': 'Arihant Superstructures Limited',
 '526125': 'Arihant Tournesol Ltd.',
 '531017': "Arihant's Securities Ltd.",
 '531677': 'Aris International Ltd.',
 '531179': 'Arman Financial Services Ltd.',
 '538556': 'Arman Holdings Ltd',
 '532397': 'Arms Paper Ltd.',
 '531467': 'Arnav Corporation Ltd.',
 '537069': 'Arnold Holdings Ltd',
 '513729': 'Aro Granite Industries Ltd.-$',
 '531560': 'Aroma Enterprises (india) Ltd.',
 '512273': 'Aroni Commercials Ltd.-$',
 '521174': 'Arora Fibres Ltd.',
 '516064': 'Arrow Greentech Ltd',
 '533068': 'Arrow Textiles Ltd.',
 '506074': 'Arshiya Limited',
 '533163': 'Arss Infrastructure Projects Ltd.',
 '517481': 'Artech Power Products Ltd.',
 '531297': 'Artefact Projects Ltd.',
 '522134': 'Artson Engineering Ltd.',
 '539301': 'Arvind Infrastructure Ltd',
 '524760': 'Arvind International Ltd.-$',
 '500101': 'Arvind Ltd.',
 '531823': 'Arvind Remedies Ltd.',
 '538716': 'Aryaman Capital Markets Ltd',
 '530245': 'Aryaman Financial Services Ltd.',
 '515030': 'Asahi India Glass Ltd.',
 '514482': 'Asahi Industries Limited',
 '512535': 'Asahi Infrastructure & Projects Ltd.',
 '532853': 'Asahi Songwon Colors Ltd.',
 '534564': 'Aseem Global Ltd.',
 '535467': 'Ashapura Intimates Fashion Ltd.',
 '527001': 'Ashapura Minechem Ltd.',
 '517565': 'Ashco Niulab Industries Ltd.-$',
 '519174': 'Ashiana Agro Industries Ltd.',
 '523716': 'Ashiana Housing Ltd.-$',
 '513401': 'Ashiana Ispat Ltd.',
 '590122': 'Ashika Credit Capital Ltd.',
 '514286': 'Ashima Ltd.',
 '512247': 'Ashirwad Capital Ltd.',
 '526847': 'Ashirwad Steels & Industries Ltd.',
 '530429': 'Ashish Polyplast Ltd.',
 '507872': 'Ashnoor Textile Mills Ltd.',
 '524594': 'Ashok Alco-chem Ltd.',
 '500477': 'Ashok Leyland Ltd.',
 '533271': 'Ashoka Buildcon Ltd.',
 '526983': 'Ashoka Refineries Ltd.',
 '526187': 'Ashram Online.com Ltd.',
 '531568': 'Ashutosh Paper Mills Ltd.',
 '538777': 'Asia Capital Ltd',
 '530899': 'Asia Pack Ltd.',
 '503940': 'Asian Electronics Ltd.',
 '531392': 'Asian Flora Ltd.',
 '532888': 'Asian Granito India Ltd.',
 '533227': 'Asian Hotels (east) Ltd.',
 '500023': 'Asian Hotels (north) Limited',
 '533221': 'Asian Hotels (west) Ltd.',
 '530355': 'Asian Oilfield Services Ltd.',
 '500820': 'Asian Paints Ltd.',
 '524434': 'Asian Petroproducts & Exports Ltd.',
 '531847': 'Asian Star Co.ltd.-$',
 '519532': 'Asian Tea & Exports Ltd.-$',
 '506159': 'Asis Logistics Limited',
 '530723': 'Asit C.mehta Financial Services Ltd.',
 '526433': 'Asm Technologies Ltd.',
 '500024': 'Assam Company (india) Limited',
 '507526': 'Associated Alcohols & Breweries Ltd.',
 '502015': 'Associated Stone Industries (kotah) Ltd.',
 '533138': 'Astec Lifesciences Limited',
 '532493': 'Astra Microwave Products Ltd.',
 '532830': 'Astral Poly Technik Ltd.',
 '506820': 'Astrazeneca Pharma India Ltd.',
 '511144': 'Asya Infosoft Limited',
 '530187': 'Atharv Enterprises Ltd.',
 '539099': 'Athena Constructions Ltd',
 '517429': 'Athena Global Technologies Ltd',
 '538713': 'Atishay Ltd',
 '526843': 'Atlanta Devcon Limited',
 '530479': 'Atlanta Infrastructure And Finance Ltd.',
 '532759': 'Atlanta Ltd.',
 '505029': 'Atlas Cycles (haryana) Ltd.',
 '514394': 'Atlas Jewellery India Limited',
 '511427': 'Atn International Ltd.',
 '531795': 'Atul Auto Ltd.-$',
 '500027': 'Atul Ltd.',
 '500028': 'Atv Projects India Ltd.',
 '532459': 'Aunde India Limited-$',
 '502352': 'Aurangabad Paper Mills Ltd.',
 '532668': 'Aurionpro Solutions Ltd.',
 '530233': 'Auro Laboratories Ltd.',
 '524804': 'Aurobindo Pharma Ltd.',
 '531336': 'Auroma Coke Ltd.',
 '530885': 'Aurum Soft Systems Limited',
 '509009': 'Ausom Enterprise Limited',
 '522005': 'Austin Engineering Co.ltd.',
 '533016': 'Austral Coke & Projects Ltd.',
 '539177': 'Authum Investment & Infrastucture Ltd',
 '532797': 'Autoline Industries Ltd.',
 '500029': 'Autolite (india) Ltd.',
 '505036': 'Automobile Corporation Of Goa Ltd.-$',
 '505010': 'Automotive Axles Ltd.',
 '520119': 'Automotive Stampings & Assemblies Ltd.',
 '500030': 'Autoriders Finance Ltd.',
 '512277': 'Autoriders International Ltd.',
 '531310': 'Available Finance Ltd.',
 '512149': 'Avance Technologies Ltd.',
 '532406': 'Avantel Ltd.',
 '512573': 'Avanti Feeds Ltd.-$',
 '523896': 'Avi Photochem Ltd.',
 '539288': 'Avi Polymers Ltd',
 '512109': 'Aviva Industries Ltd.',
 '532995': 'Avon Corporation Ltd.',
 '531541': 'Avon Lifesciences Ltd-$',
 '511589': 'Avonmore Capital & Management Services Limited',
 '519105': 'Avt Natural Products Ltd.',
 '504390': 'Avtil Enterprise Ltd',
 '513642': 'Axel Polymers Ltd.',
 '532215': 'Axis Bank Ltd.',
 '532395': 'Axiscades Engineering Technologies Ltd',
 '505506': 'Axon Ventures Ltd',
 '523850': 'Axtel Industries Ltd.',
 '508933': 'Aym Syntex Ltd',
 '512063': 'Ayoki Mercantile Ltd.',
 '531783': 'Azure Exim Services Ltd.',
 '508136': 'B & A Ltd.',
 '523186': 'B&a Packaging India Limited',
 '506971': 'B&b Realty Limited',
 '536965': 'B. P. Capital Ltd',
 '532507': 'B.a.g.films & Media Ltd.',
 '537766': 'B.c. Power Controls Ltd',
 '532719': 'B.l.kashyap And Sons Ltd.',
 '523019': 'B.n.rathi Securities Ltd.',
 '526594': 'B.nanji Enterprises Ltd.',
 '531268': 'B2b Software Technologies Ltd.',
 '532380': 'Baba Arts Ltd.-$',
 '524516': 'Bacil Pharma Ltd.',
 '532989': 'Bafna Pharmaceuticals Ltd.',
 '530197': 'Bagadia Colourchem Ltd.',
 '511724': 'Baid Leasing And Finance Co.ltd.',
 '532977': 'Bajaj Auto Ltd.',
 '533229': 'Bajaj Corp Ltd.',
 '500031': 'Bajaj Electricals Ltd.-$',
 '500034': 'Bajaj Finance Limited',
 '532978': 'Bajaj Finserv Ltd.',
 '512261': 'Bajaj Global Ltd.',
 '500032': 'Bajaj Hindusthan Sugar Limited',
 '500490': 'Bajaj Holdings & Investment Ltd.',
 '507944': 'Bajaj Steel Industries Ltd.',
 '511139': 'Bajrang Finance Ltd.',
 '524824': 'Bal Pharma Ltd.',
 '511395': 'Bala Techno Global Ltd.',
 '514199': 'Bala Techno Industries Ltd.',
 '530999': 'Balaji Amines Ltd.-$',
 '532382': 'Balaji Telefilms Ltd.',
 '513142': 'Balasore Alloys Ltd.',
 '502355': 'Balkrishna Industries Ltd.-$',
 '500102': 'Ballarpur Industries Ltd.',
 '523319': 'Balmer Lawrie & Co.ltd.',
 '532485': 'Balmer Lawrie Investments Ltd.',
 '500038': 'Balrampur Chini Mills Ltd.',
 '520127': 'Balurghat Technologies Ltd.',
 '519295': 'Bambino Agro Industries Ltd.',
 '531591': 'Bampsl Securities Ltd.',
 '526849': 'Banaras Beads Ltd.',
 '509053': 'Banas Finance Ltd.',
 '500039': 'Banco Products (india) Ltd.-$',
 '532946': 'Bang Overseas Ltd.',
 '539120': 'Bangalore Fort Farms Ltd',
 '532134': 'Bank Of Baroda',
 '532149': 'Bank Of India',
 '532525': 'Bank Of Maharashtra',
 '532674': 'Bannari Amman Spinning Mills Ltd.',
 '500041': 'Bannari Amman Sugars Ltd.',
 '538546': 'Bansal Roofing Products Ltd',
 '503722': 'Banswara Syntex Ltd.-$',
 '532916': 'Barak Valley Cements Ltd.',
 '513502': 'Baroda Extrusion Ltd.',
 '532336': 'Baron Infotech Ltd.',
 '532694': 'Bartronics India Ltd.',
 '524687': 'Basant Agro Tech (india) Ltd.-$',
 '500042': 'Basf India Ltd.',
 '511210': 'Basil Infrastructure Projects Ltd.',
 '500043': 'Bata India Ltd.',
 '522004': 'Batliboi Ltd.-$',
 '506285': 'Bayer Cropscience Ltd.',
 '517246': 'Bcc Fuba India Ltd.',
 '524332': 'Bcl Industries And Infrastructures Ltd-$',
 '524828': 'Bdh Industries Ltd.',
 '539447': 'Beardsell Ltd',
 '531937': 'Beckons Industries Ltd.',
 '533270': 'Bedmutha Industries Ltd.',
 '539018': 'Beekay Steel Industries Ltd',
 '532645': 'Beeyu Overseas Ltd.',
 '531112': 'Bell Agromachina Ltd.',
 '539399': 'Bella Casa Fashion & Retail Ltd',
 '522650': 'Bemco Hydraulics Ltd.',
 '500048': 'Beml Ltd.',
 '509438': 'Benares Hotels Ltd.',
 '533095': 'Bengal & Assam Company Ltd.',
 '532230': 'Bengal Tea & Fabrics Ltd.',
 '512195': 'Bentley Commercial Enterprises Ltd.',
 '524737': 'Benzo Petro International Ltd.',
 '509480': 'Berger Paints India Ltd.',
 '531340': 'Bervin Investment & Leasing Ltd.',
 '524606': 'Beryl Drugs Ltd.',
 '531582': 'Beryl Securities Ltd.',
 '500046': 'Best & Crompton Engg.ltd.',
 '508664': 'Best Eastern Hotels Ltd.',
 '531481': 'Beta-kappa Investments Ltd.',
 '512477': 'Betex India Ltd.',
 '533303': 'Bf Investment Ltd.',
 '532430': 'Bf Utilities Ltd.-$',
 '511664': 'Bgil Films & Technologies Ltd.',
 '532930': 'Bgr Energy Systems Ltd.',
 '500051': 'Bhagawati Gas Limited',
 '530803': 'Bhageria Industries Ltd',
 '531719': 'Bhagiradha Chemicals & Industries Ltd.',
 '530095': 'Bhagwandas Metals Ltd.',
 '504646': 'Bhagwati Autocast Ltd.',
 '509449': 'Bhagwati Oxygen Ltd.',
 '512296': 'Bhagyanagar India Ltd.',
 '511698': 'Bhagyashree Leasing & Finance Ltd.',
 '501233': 'Bhagyodaya Infrastructure Development Ltd',
 '512608': 'Bhandari Hosiery Exports Ltd.',
 '538576': 'Bhanderi Infracon Ltd',
 '534740': 'Bhanot Construction & Housing Ltd.',
 '500052': 'Bhansali Engineering Polymers Ltd.-$',
 '531862': 'Bharat Agri Fert & Realty Ltd.',
 '511501': 'Bharat Bhushan Share & Commodity Brokers Ltd.',
 '503960': 'Bharat Bijlee Ltd.-$',
 '500049': 'Bharat Electronics Ltd.',
 '500493': 'Bharat Forge Ltd.',
 '505688': 'Bharat Gears Ltd.',
 '500103': 'Bharat Heavy Electricals Ltd.',
 '524663': 'Bharat Immunologicals & Biologicals Corporation Ltd.-$',
 '500547': 'Bharat Petroleum Corporation Ltd.',
 '590021': 'Bharat Rasayan Ltd.',
 '523229': 'Bharat Seats Ltd.-$',
 '531029': 'Bharat Textiles & Proofing Industries Ltd.',
 '532609': 'Bharati Shipyard Ltd.',
 '533499': 'Bharatiya Global Infomedia Ltd.',
 '532454': 'Bharti Airtel Ltd.',
 '534816': 'Bharti Infratel Ltd.',
 '526666': 'Bhartiya International Ltd.',
 '518017': 'Bheema Cements Ltd.',
 '514272': 'Bhilwara Spinners Ltd.',
 '533108': 'Bhilwara Technical Textiles Ltd.',
 '530879': 'Bhilwara Tex-fin Ltd.',
 '506027': 'Bhoruka Aluminium Ltd.',
 '500055': 'Bhushan Steel Ltd.',
 '513333': 'Bhuwalka Steel Industries Ltd.-$',
 '500058': 'Bihar Sponge Iron Ltd.',
 '512313': 'Bijlee Textiles Ltd.',

In [5]:
from bsedata.bse import BSE

def get_real_time_stock_price(stock_code):
    bse = BSE(update_codes=True)  # Initialize BSE object with update_codes = True for real-time data
    stock_data = bse.getQuote(stock_code)
    if stock_data:
        return stock_data['currentValue']
    else:
        return None

def main():
    stock_code = '500209'  # Example: infosys stock code
    real_time_price = get_real_time_stock_price(stock_code)
    if real_time_price:
        print(f"Real-time price for stock with code {stock_code}: {real_time_price}")
    else:
        print(f"Unable to fetch real-time price for stock with code {stock_code}")

#if __name__ == "__main__":
    main()

In [4]:
bse.getIndices("sector_and_industry")

{'updatedOn': '20 Mar 2024',
 'indices': [{'currentValue': '6,353.73',
   'change': '-41.80',
   'pChange': '-0.65',
   'scripFlag': '88',
   'name': 'S&P BSE Commodities'},
  {'currentValue': '8,224.46',
   'change': '+24.88',
   'pChange': '0.30',
   'scripFlag': '89',
   'name': 'S&P BSE Consumer Discretionary'},
  {'currentValue': '11,579.31',
   'change': '+124.45',
   'pChange': '1.09',
   'scripFlag': '90',
   'name': 'S&P BSE Energy'},
  {'currentValue': '18,983.96',
   'change': '+89.39',
   'pChange': '0.47',
   'scripFlag': '83',
   'name': 'S&P BSE Fast Moving Consumer Goods'},
  {'currentValue': '10,051.10',
   'change': '-36.79',
   'pChange': '-0.36',
   'scripFlag': '91',
   'name': 'S&P BSE Financial Services'},
  {'currentValue': '33,770.41',
   'change': '+73.57',
   'pChange': '0.22',
   'scripFlag': '84',
   'name': 'S&P BSE Healthcare'},
  {'currentValue': '11,781.73',
   'change': '+26.66',
   'pChange': '0.23',
   'scripFlag': '92',
   'name': 'S&P BSE Industrials'},
  {'currentValue': '36,249.45',
   'change': '-106.59',
   'pChange': '-0.29',
   'scripFlag': '85',
   'name': 'S&P BSE Information Technology'},
  {'currentValue': '2,408.40',
   'change': '+14.58',
   'pChange': '0.61',
   'scripFlag': '96',
   'name': 'S&P BSE Telecommunication'},
  {'currentValue': '5,186.50',
   'change': '+23.26',
   'pChange': '0.45',
   'scripFlag': '97',
   'name': 'S&P BSE Utilities'},
  {'currentValue': '46,847.19',
   'change': '+219.18',
   'pChange': '0.47',
   'scripFlag': '42',
   'name': 'S&P BSE AUTO'},
  {'currentValue': '52,595.65',
   'change': '-47.54',
   'pChange': '-0.09',
   'scripFlag': '53',
   'name': 'S&P BSE BANKEX'},
  {'currentValue': '56,480.48',
   'change': '+126.43',
   'pChange': '0.22',
   'scripFlag': '25',
   'name': 'S&P BSE CAPITAL GOODS'},
  {'currentValue': '49,863.90',
   'change': '-65.10',
   'pChange': '-0.13',
   'scripFlag': '27',
   'name': 'S&P BSE CONSUMER DURABLES'},
  {'currentValue': '26,903.53',
   'change': '-235.04',
   'pChange': '-0.87',
   'scripFlag': '35',
   'name': 'S&P BSE METAL'},
  {'currentValue': '26,725.20',
   'change': '+282.50',
   'pChange': '1.07',
   'scripFlag': '37',
   'name': 'S&P BSE OIL & GAS'},
  {'currentValue': '6,316.50',
   'change': '+57.54',
   'pChange': '0.92',
   'scripFlag': '69',
   'name': 'S&P BSE POWER'},
  {'currentValue': '6,587.98',
   'change': '+33.98',
   'pChange': '0.52',
   'scripFlag': '67',
   'name': 'S&P BSE REALTY'},
  {'currentValue': '16,395.30',
   'change': '-26.01',
   'pChange': '-0.16',
   'scripFlag': '45',
   'name': 'S&P BSE TECK'},
  {'currentValue': '1,299.90',
   'change': '+1.35',
   'pChange': '0.10',
   'scripFlag': '121',
   'name': 'S&P BSE Services'},
  {'currentValue': '126.87',
   'change': '-1.86',
   'pChange': '-1.44',
   'scripFlag': 'SPBRIIP',
   'name': 'S&P BSE REIT & InvIT Index (INR)'}]}

In [7]:
from bsedata.bse import BSE

def get_real_time_stock_price(stock_code):
    bse = BSE(update_codes=True)  # Initialize BSE object with update_codes = True for real-time data
    stock_data = bse.getQuote(stock_code)
    if stock_data:
        return stock_data['currentValue']
    else:
        return None

def main():
    stock_code = '500209'  # Example: infosys stock code
    real_time_price = get_real_time_stock_price(stock_code)
    if real_time_price:
        print(f"Real-time price for stock with code {stock_code}: {real_time_price}")
    else:
        print(f"Unable to fetch real-time price for stock with code {stock_code}")